=== GameRuiner/Uniwersytet/VII semestr/WWW/Lista5/tint-p04a-xml/produkty1.xsd
<?xml version="1.0" encoding="ISO-8859-2"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="dostawy">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="dostawa" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="data_dostawy" type="xs:date"/>	    
            <xs:element name="produkt" maxOccurs="unbounded">
	      <xs:complexType>
	        <xs:sequence>
	          <xs:element name="nazwa" type="xs:string"/>
	          <xs:element name="ilosc" type="xs:integer"/>
	          <xs:element name="jednostka">
		    <xs:simpleType>
		      <xs:restriction base="xs:string">
		        <xs:enumeration value="szt."/>
			<xs:enumeration value="kg"/>
			<xs:enumeration value="dkg"/>
		      </xs:restriction>
		    </xs:simpleType>
		  </xs:element>
	          <xs:element name="cena">
	            <xs:simpleType>
		      <xs:restriction base="xs:decimal">
		        <xs:fractionDigits value="2"/>
		      </xs:restriction>
		    </xs:simpleType>
	          </xs:element>
	        </xs:sequence>
	        <xs:attribute name="produktid" use="required">
		  <xs:simpleType>
		    <xs:restriction base="xs:string">
		      <xs:pattern value="[0-9]{5}"/>
		    </xs:restriction>
		  </xs:simpleType>
		</xs:attribute>
	      </xs:complexType>
	    </xs:element>
            <xs:element name="dostawca">
	      <xs:complexType>
	        <xs:sequence>
	          <xs:element name="nazwa" type="xs:string"/>
	          <xs:element name="adres" type="xs:string"/>
                  <xs:element name="tel_stacjonarny" type="xs:string" minOccurs="0" maxOccurs="1"/>
		  <xs:element name="tel_komorkowy" type="xs:string" minOccurs="0" maxOccurs="1"/>
	        </xs:sequence>
	      </xs:complexType>
	    </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== GameRuiner/Uniwersytet/VII semestr/WWW/Lista5/tint-p04a-xml/produkty1.xml
<?xml version="1.0" encoding="ISO-8859-2"?>

<dostawy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="produkty1.xsd">


<dostawa>
<data_dostawy>2005-10-10</data_dostawy>
<produkt produktid="44324">
 <nazwa>Batonik Kitkat</nazwa>
 <ilosc>152</ilosc>
 <jednostka>szt.</jednostka>
 <cena>1.50</cena>
</produkt>
<produkt produktid="22322">
 <nazwa>Batonik Snickers</nazwa>
 <ilosc>77</ilosc>
 <jednostka>szt.</jednostka>
 <cena>1.72</cena>
</produkt>
<dostawca>
 <nazwa>Kogucik S.A.</nazwa>
 <adres>ul. Ptasia 20</adres>
 <tel_stacjonarny>71/333 44 55 66</tel_stacjonarny>
</dostawca>
</dostawa>

</dostawy>
